spring.application.name=lab-sample-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/labdb

spring.datasource.username=postgres

spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
# That command tells hibernate to automatically create or update your database tables based on your entity classes

spring.jpa.show-sql=true
# Shows sql on console
springdoc.swagger-ui.url=/v3/api-docs
server.forward-headers-strategy=framework